### ISSUE TITLE
Shared volume issue

### ISSUE THREAD

**Issue by mtraul** [stain/jena-docker#1]
Hi,

I am trying to run stain/jena-fuseki with a shared volume [1] and run into a weird issue.

[1] https://hub.docker.com/r/stain/jena-fuseki/#data-persistence

First, I start fresh:

[[
mkdir /Users/mtraul/Projects/fuseki-test/
]]

Then I start the container:

[[
docker run -it -p 3030:3030 -e ADMIN_PASSWORD=12345 -v /Users/mtraul/Projects/fuseki-test:/fuseki --rm stain/jena-fuseki
]]

Then when I try to create a dataset from the web interface, I get the following error :

[[
###################################
Initializing Apache Jena Fuseki

###################################
[2015-09-28 22:55:30] Server     INFO  Fuseki 2.3.0 2015-07-25T17:11:28+0000
[2015-09-28 22:55:30] Config     INFO  FUSEKI_HOME=/jena-fuseki
[2015-09-28 22:55:30] Config     INFO  FUSEKI_BASE=/fuseki
[2015-09-28 22:55:30] Servlet    INFO  Initializing Shiro environment
[2015-09-28 22:55:30] Config     INFO  Shiro file: file:///fuseki/shiro.ini
[2015-09-28 22:55:31] Server     INFO  Started 2015/09/28 22:55:31 GMT on port 3030
[2015-09-28 22:55:38] Admin      INFO  [1] GET http://192.168.99.100:3030/$/server
[2015-09-28 22:55:38] Admin      INFO  [1] 200 OK (15 ms)
[2015-09-28 22:55:44] Admin      INFO  [2] POST http://192.168.99.100:3030/$/datasets
[2015-09-28 22:55:44] Admin      INFO  [2] Create database : name = /foobar
[2015-09-28 22:55:45] Admin      WARN  [2] RC = 500 : caught: BlockMgrMapped.segmentAllocate: Segment = 0
org.apache.jena.assembler.exceptions.AssemblerException: caught: BlockMgrMapped.segmentAllocate: Segment = 0
 doing:
   root: http://base/#tdb_dataset_readwrite with type: http://jena.hpl.hp.com/2008/tdb#DatasetTDB assembler class: class org.apache.jena.tdb.assembler.DatasetAssemblerTDB

	at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:138)
	at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.open(AssemblerGroup.java:117)
	at org.apache.jena.assembler.assemblers.AssemblerGroup$ExpandingAssemblerGroup.open(AssemblerGroup.java:81)
	at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:37)
	at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:33)
	at org.apache.jena.fuseki.build.Builder.buildDataService(Builder.java:74)
	at org.apache.jena.fuseki.build.Builder.buildDataAccessPoint(Builder.java:59)
	at org.apache.jena.fuseki.mgt.ActionDatasets.execPostContainer(ActionDatasets.java:188)
	at org.apache.jena.fuseki.mgt.ActionContainerItem.execPost(ActionContainerItem.java:87)
	at org.apache.jena.fuseki.mgt.ActionContainerItem.perform(ActionContainerItem.java:62)
	at org.apache.jena.fuseki.mgt.ActionCtl.executeLifecycle(ActionCtl.java:76)
	at org.apache.jena.fuseki.mgt.ActionCtl.executeAction(ActionCtl.java:67)
	at org.apache.jena.fuseki.mgt.ActionCtl.execCommonWorker(ActionCtl.java:57)
	at org.apache.jena.fuseki.servlets.ActionBase.doCommon(ActionBase.java:79)
	at org.apache.jena.fuseki.mgt.ActionContainerItem.doPost(ActionContainerItem.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:717)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1644)
	at org.apache.jena.fuseki.servlets.FusekiFilter.doFilter(FusekiFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1632)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1624)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:459)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.jena.tdb.base.file.FileException: BlockMgrMapped.segmentAllocate: Segment = 0
	at org.apache.jena.tdb.base.file.BlockAccessMapped.allocSegment(BlockAccessMapped.java:231)
	at org.apache.jena.tdb.base.file.BlockAccessMapped.getByteBuffer(BlockAccessMapped.java:157)
	at org.apache.jena.tdb.base.file.BlockAccessMapped.allocate(BlockAccessMapped.java:85)
	at org.apache.jena.tdb.base.block.BlockMgrFileAccess.allocate(BlockMgrFileAccess.java:50)
	at org.apache.jena.tdb.base.block.BlockMgrBase.allocate(BlockMgrBase.java:44)
	at org.apache.jena.tdb.base.block.BlockMgrWrapper.allocate(BlockMgrWrapper.java:46)
	at org.apache.jena.tdb.base.block.BlockMgrFreeChain.allocate(BlockMgrFreeChain.java:48)
	at org.apache.jena.tdb.base.page.PageBlockMgr.create(PageBlockMgr.java:51)
	at org.apache.jena.tdb.index.bplustree.BPTreeRecordsMgr.create(BPTreeRecordsMgr.java:79)
	at org.apache.jena.tdb.index.bplustree.BPTreeNodeMgr.createEmptyBPT(BPTreeNodeMgr.java:52)
	at org.apache.jena.tdb.index.bplustree.BPlusTree.createIfAbsent(BPlusTree.java:213)
	at org.apache.jena.tdb.index.bplustree.BPlusTree.create(BPlusTree.java:139)
	at org.apache.jena.tdb.index.BuilderStdIndex$RangeIndexBuilderStd.createBPTree(BuilderStdIndex.java:94)
	at org.apache.jena.tdb.index.BuilderStdIndex$RangeIndexBuilderStd.buildRangeIndex(BuilderStdIndex.java:65)
	at org.apache.jena.tdb.index.BuilderStdIndex$IndexBuilderStd.buildIndex(BuilderStdIndex.java:47)
	at org.apache.jena.tdb.setup.BuilderStdDB$NodeTableBuilderStd.buildNodeTable(BuilderStdDB.java:72)
	at org.apache.jena.tdb.setup.DatasetBuilderStd$NodeTableBuilderRecorder.buildNodeTable(DatasetBuilderStd.java:423)
	at org.apache.jena.tdb.setup.DatasetBuilderStd.makeNodeTable(DatasetBuilderStd.java:323)
	at org.apache.jena.tdb.setup.DatasetBuilderStd.buildWorker(DatasetBuilderStd.java:204)
	at org.apache.jena.tdb.setup.DatasetBuilderStd._build(DatasetBuilderStd.java:198)
	at org.apache.jena.tdb.setup.DatasetBuilderStd.build(DatasetBuilderStd.java:187)
	at org.apache.jena.tdb.setup.DatasetBuilderStd.create(DatasetBuilderStd.java:91)
	at org.apache.jena.tdb.StoreConnection.make(StoreConnection.java:228)
	at org.apache.jena.tdb.StoreConnection.make(StoreConnection.java:235)
	at org.apache.jena.tdb.transaction.DatasetGraphTransaction.<init>(DatasetGraphTransaction.java:73)
	at org.apache.jena.tdb.sys.TDBMaker._create(TDBMaker.java:58)
	at org.apache.jena.tdb.sys.TDBMaker.createDatasetGraphTransaction(TDBMaker.java:46)
	at org.apache.jena.tdb.TDBFactory._createDatasetGraph(TDBFactory.java:82)
	at org.apache.jena.tdb.TDBFactory.createDatasetGraph(TDBFactory.java:64)
	at org.apache.jena.tdb.assembler.DatasetAssemblerTDB.make(DatasetAssemblerTDB.java:57)
	at org.apache.jena.tdb.assembler.DatasetAssemblerTDB.createDataset(DatasetAssemblerTDB.java:48)
	at org.apache.jena.sparql.core.assembler.DatasetAssembler.open(DatasetAssembler.java:45)
	at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:130)
	... 54 more
Caused by: java.io.IOException: Invalid argument
	at sun.nio.ch.FileChannelImpl.map0(Native Method)
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:925)
	at org.apache.jena.tdb.base.file.BlockAccessMapped.allocSegment(BlockAccessMapped.java:223)
	... 86 more
[2015-09-28 22:55:45] Admin      INFO  [2] 500 caught: BlockMgrMapped.segmentAllocate: Segment = 0 (625 ms)
]]

The same operation works ok when using fuseki outside of the container.

Note: I have the same problem when using stain/jena-fuseki:devel.

Anybody has an idea of what's going on?

Thanks

**Comment by betehess** [comment]
After playing with that, I have an idea: I know that VirtualBox has issues with memory mapping in shared folders. And on OSX, [`/Users` gets shared with the host through VirtualBox](https://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume). So if Fuseki/TDB somehow relies on some kind of `mmap` then this won't work.

**Comment by afs** [comment]
Yes, TDB uses mmap files.

So it's the use of `/Users/` that is causing the problem? and a volume mount from the VM OS will  work. 

Could someone please try that - I don't have access to a setup to test it.  It all works on Ubuntu (i.e. without a VM in the way).

https://www.virtualbox.org/pipermail/vbox-dev/2013-April/011349.html
explains the situation.

**Comment by afs** [comment]
It is possible to run TDB with direct file access, instead of using mapped files.

The command line argument to switch it is `--set tdb:fileMode=direct`

Databases are compatible across the two modes.

If the database is large and queries complex, it may be worth doing some cache tuning:

https://jena.apache.org/documentation/tdb/store-parameters.html

but this may not be needed at all depending on usage.

**Comment by BioQwer** [comment]
Hello!
I have OSX, docker running in VirtualBox.
This issue not about Jena, it's some config or speciality of VM.
I have same problem with persist data on another product like mysql, postgres.

My solution is create directory in VM and use them for persist data.
BootToDocker create virtual disk on `/mnt/sda1/`, let's use this space.
`mkdir /mnt/sda1/var/lib/jena`
`chmod 777 /mnt/sda1/var/lib/jena`
`docker run -d -v /mnt/sda1/var/lib/jena:/fuseki --name=fusekidata -p 3030:3030 -e ADMIN_PASSWORD=pw123 -it stain/jena-fuseki`

At this way data persist.

**Comment by stain** [comment]
sorry I missed this - I'll close this bug, assuming @BioQwer's workaround works for you, @mtraul ?

I think to formalize this you would need to use Docker Machine, the Dockerfile can't say anything about how the volumes will be made.
