### ISSUE TITLE
Error BlockMgrMapped.segmentAllocate

### ISSUE THREAD

**Issue by TamouzeAssi** [stain/jena-docker#4]
Hello,

Im trying to parse a big file. The program runs very well and all it was ok. After 17h of runing i get the following exception:

com.hp.hpl.jena.tdb.base.file.FileException: BlockMgrMapped.segmentAllocate: Segment = 62 : Offset = 520093696
        at com.hp.hpl.jena.tdb.base.file.BlockAccessMapped.allocSegment(BlockAccessMapped.java:229)
        at com.hp.hpl.jena.tdb.base.file.BlockAccessMapped.getByteBuffer(BlockAccessMapped.java:156)
        at com.hp.hpl.jena.tdb.base.file.BlockAccessMapped.allocate(BlockAccessMapped.java:84)
        at com.hp.hpl.jena.tdb.base.block.BlockMgrFileAccess.allocate(BlockMgrFileAccess.java:51)
        at com.hp.hpl.jena.tdb.base.block.BlockMgrBase.allocate(BlockMgrBase.java:44)
        at com.hp.hpl.jena.tdb.base.block.BlockMgrWrapper.allocate(BlockMgrWrapper.java:46)
        at com.hp.hpl.jena.tdb.base.block.BlockMgrFreeChain.allocate(BlockMgrFreeChain.java:48)
        at com.hp.hpl.jena.tdb.base.page.PageBlockMgr.create(PageBlockMgr.java:52)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeRecordsMgr.create(BPTreeRecordsMgr.java:79)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeRecords.create(BPTreeRecords.java:208)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeRecords.split(BPTreeRecords.java:182)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNode.split(BPTreeNode.java:519)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNode.internalInsert(BPTreeNode.java:455)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNode.internalInsert(BPTreeNode.java:468)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNode.internalInsert(BPTreeNode.java:468)
        at com.hp.hpl.jena.tdb.index.bplustree.BPTreeNode.insert(BPTreeNode.java:212)
        at com.hp.hpl.jena.tdb.index.bplustree.BPlusTree.addAndReturnOld(BPlusTree.java:327)
        at com.hp.hpl.jena.tdb.index.bplustree.BPlusTree.add(BPlusTree.java:319)
        at com.hp.hpl.jena.tdb.store.tupletable.TupleIndexRecord.performAdd(TupleIndexRecord.java:62)
        at com.hp.hpl.jena.tdb.store.tupletable.TupleIndexBase.add(TupleIndexBase.java:64)
        at com.hp.hpl.jena.tdb.store.tupletable.TupleTable.add(TupleTable.java:96)
        at com.hp.hpl.jena.tdb.store.nodetupletable.NodeTupleTableConcrete.addRow(NodeTupleTableConcrete.java:88)
        at com.hp.hpl.jena.tdb.store.TripleTable.add(TripleTable.java:58)
        at com.hp.hpl.jena.tdb.store.DatasetGraphTDB.addToDftGraph(DatasetGraphTDB.java:99)
        at com.hp.hpl.jena.sparql.core.DatasetGraphTriplesQuads.add(DatasetGraphTriplesQuads.java:47)
        at com.hp.hpl.jena.sparql.core.GraphView.performAdd(GraphView.java:141)
        at com.hp.hpl.jena.tdb.store.GraphTDB.performAdd(GraphTDB.java:87)
        at com.hp.hpl.jena.graph.impl.GraphBase.add(GraphBase.java:202)
        at org.apache.jena.riot.system.StreamRDFLib$ParserOutputGraph.triple(StreamRDFLib.java:163)
        at org.apache.jena.riot.lang.LangTurtle.emit(LangTurtle.java:58)
        at org.apache.jena.riot.lang.LangTurtleBase.emitTriple(LangTurtleBase.java:488)
        at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:351)
        at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:288)
        at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:269)
        at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:250)
        at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:191)
        at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:47)
        at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:90)
        at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:42)
        at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:185)
        at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:906)
        at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:687)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:210)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:143)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:132)
        at org.apache.jena.riot.adapters.AdapterFileManager.readModelWorker(AdapterFileManager.java:283)
        at com.hp.hpl.jena.util.FileManager.readModel(FileManager.java:342)
        at de.dwslab.petar.walks.Connection.load_dumps(Connection.java:75)
        at de.dwslab.petar.walks.Connection.<init>(Connection.java:49)
        at de.dwslab.petar.walks.SurfaceForms.main(SurfaceForms.java:285)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:745)

Im working on a SSH linux server. Any advice it appreciated.
Thank you in advance

**Comment by stain** [comment]
You can increase the memory allocated to Jena with the Docker parameter ` -e JVM_ARGS=-Xmx2g` (for 2 GB).

If you still have trouble, try running it outside Docker from the [Jena Fuseki download](http://jena.apache.org/download/) and Oracle JDK 8 - then report back to [Apache Jena](http://jena.apache.org/help_and_support/bugs_and_suggestions.html) if you still have trouble.

**Comment by stain** [comment]
Sorry I didn't spot this before, your traceback mentions `com.hp.hpl.jena.graph.impl` which indicates outdated Jena 2.x. 

The latest [Apache Jena download](jena.apache.org/download/) is 3.6.0 (which uses `org.apache.jena.*`)

Closing as out of scope for this Docker image.
